name: Test Get Email from Github Username
on:
  workflow_dispatch:
    inputs:
      username:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-text: './.github/tweet_template.txt'
          'user:default/': ''
  get_user_email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    steps:
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ inputs.username }}

      # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"
