name: Test Get Email from Github Username
on:
  workflow_dispatch:
    inputs:
      username:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  params:
      name: 'Set parameters'
      runs-on: ubuntu-latest
      outputs:
          owner: ${{ steps.set-variable.outputs.owner }}
          version: ${{ steps.set-variable.outputs.version }}
          retention: ${{ steps.set-variable.outputs.retention }}
      steps:
        - name: Prepare github username
          shell: bash
          id: replace-username
          run: |
              echo 'replacing username'
        - name: Check params
          shell: bash
          id: set-variable
          run: |
              echo "owner=ilkaykisayol@gmail.com" >> "$GITHUB_OUTPUT"
          # TODO: verify email, should be a valid email address using Regecx and possibly only be within AZ org.
          # Also, does this need to be a specific set of users?
  get_user_email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    steps:
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ steps.params.outputs.owner }}

      # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"
