name: Test send mail
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  find-and-replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read and Modify File
        run: |
          # Read the file content and store it in a variable
          FILE_CONTENT=$(cat ./on-demand-created.html)
          echo "$FILE_CONTENT"
