name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "on-demand-created.html"

      - name: File contents
        run: echo "${ steps.file_contents.outputs.contents }"
