name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - uses: flcdrg/replace-multiple-action@v1
        with:
            files: './*.md'
            find: '[{ "find": "http://localhost", "replace": "https://localhost"}, { "find": "http://davidgardiner.net.au", "replace": "https://david.gardiner.net.au" }]'
            prefix: '(^|\\s+|\\()'
            suffix: '($|\\s+|\\))'
