name: Test send mail
on:
    workflow_dispatch: # on demand
        inputs:
            owner:
                description: 'Github username of the environment owner'
                required: true
                type: string
            version:
                description: 'Choose application and environment version'
                required: true
                type: choice
                options: 
                - 'Boost 1.1'
                - 'Boost 1.2'
                default: 'Boost 1.2'
            retention:
                description: 'Choose retention period - environment will be decommissioned after this period'
                required: true
                type: choice
                options: 
                - '1 week'
                - '2 weeks'
                - '4 weeks'
                - '8 weeks'
                - '10 weeks'
                default: '2 weeks'

jobs:
  params:
      name: Set parameters
      runs-on: ubuntu-latest
      outputs:
          owner: ${{ steps.set-variable.outputs.owner }}
      steps:
        - name: Prepare github username
          shell: bash
          id: replace-username
          run: |
              backstageUserName=${{ inputs.owner }}
              replaceValue="user:default/"   
              echo "username="${backstageUserName//$replaceValue}"" >> "$GITHUB_OUTPUT"
        - name: Check params
          shell: bash
          id: set-variable
          run: |
              echo "owner=${{ steps.replace-username.outputs.username }}" >> "$GITHUB_OUTPUT"
  get_user_email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    needs: params
    outputs:
          email: ${{ steps.find-email.outputs.email }}
    steps:
      - name: Find email
        id: find-email
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ needs.params.outputs.owner }}
  send_mail:
    runs-on: ubuntu-latest
    name: A job to send an email to user
    needs: [get_user_email, params]
    steps:
      - uses: actions/checkout@v2
      - name: Replace HTML File
        id: replace-mail-body
        run: |
          # Read the file content and store it in a variable
          FILE_CONTENT=$(cat ./on-demand-created.html)
          FILE_CONTENT="${FILE_CONTENT//##OWNER##/${{ needs.params.outputs.owner }}}"
          FILE_CONTENT="${FILE_CONTENT//##VERSION##/${{ inputs.version }}}"
          FILE_CONTENT="${FILE_CONTENT//##RETENTION##/${{ inputs.retention }}}"
          echo "body="$FILE_CONTENT"" >> "$GITHUB_OUTPUT"
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: smtp.office365.com
          # Server port, default 25:
          server_port: 587
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: On-Demand Environment Creation
          # Required recipients' addresses:
          to: ilkay.kisayol@astrazeneca.com # ${{ needs.get_user_email.outputs.email }}
          # Required sender full name (address can be skipped):
          from: No Reply # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          html_body: ${{ steps.replace-mail-body.outputs.body }}
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
