name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  read_content:
    runs-on: ubuntu-latest
    name: A job to read mail template
    steps:
      - name: List Files
        run: |
          ls -R
      - name: Read VERSION file
        id: getContent
        run: echo "content=$(cat pocboost/on-demand-created.html)" >> $GITHUB_OUTPUT
      # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.getContent.outputs.content }}"
