name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  find-and-replace:
    runs-on: ubuntu-latest
    steps:
      - name: Find and replace string
        uses: actions/find-and-replace@v2
        with:
          find: "old value"
          replace: "new value"
          files: on-demand-created.html
