name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: flcdrg/replace-multiple-action@v1
        with:
          files: './*.html'
          find: '[{ "{owner}": "Multiple", "replace": "Many" }]'
