name: Test Get Email from Github Username and read content
on:
  workflow_dispatch:
    inputs:
      owner:
          description: 'Github username of the environment owner'
          required: true
          type: string

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./on-demand-created.html
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
